### ISSUE TITLE
1.1: Seer crashes when fast-forwarding with .avi video files

### ISSUE THREAD

**Issue by vrodionov** [ccseer/Seer#62]
This is an issue specific to the latest 1.1 version.
It has not been a problem with either 0.7.5 or 0.8.

Seer crashes when fast-forwarding .avi video files. Steps to reproduce:
1. Press space to preview a video. It starts playing.
2. Click anywhere on the video progress bar. The video marker will move to the location of the click. Playback will stop, and an MS Visial C++ Runtime Library crash dialog will appear (screenshot attached). Seer will need to be restarted in order to use it again.

The bug manifests itself specifically with .avi container files. The particuilar codec does not seem to matter. Furthermore, if the .avi file is not fast-forwarded, Seer does not crash.

Seer works fine with Matroska .mkv, .mp4, .mov, .mpg .wmv and even .flv. 
![seer crash](https://cloud.githubusercontent.com/assets/1922226/19490693/cf0049e6-9578-11e6-9250-30ad99016445.png)

**Comment by ccseer** [comment]
You mean all the .avi video files?

Would you please send me one .avi which might make Seer crash,

**Comment by vrodionov** [comment]
Hi,

 

Here is an example of a file that crashes Seer:

 

https://app.box.com/s/uq19hb7lqp2jr2m57fhrpr0o2crbglvs

 

However, in my experience *any* .avi file crashes it – as long as it is .avi.

I tried a few with different codecs, and the result is always the same.

Cheers,

 

Valentin

**Comment by ccseer** [comment]
Thx.

I will look into it. And try to fix it in next release.

**Comment by vrodionov** [comment]
If it helps any more, here is the event description from Event Viewer:

 

 

Faulting application name: Seer.exe, version: 0.8.0.0, time stamp: 0x5804be3c

Faulting module name: avformat-57.dll, version: 0.0.0.0, time stamp: 0x00000000

Exception code: 0x40000015

Fault offset: 0x0001753f

Faulting process id: 0x14a0

Faulting application start time: 0x01d229e793a62de4

Faulting application path: C:\Program Files (x86)\Seer\Seer.exe

Faulting module path: C:\Program Files (x86)\Seer\avformat-57.dll

Report Id: f619e139-7157-4639-a7f6-66c269207b3d

Faulting package full name: 

Faulting package-relative application ID:

 

So it is in the avformat-57.dll.

 

Also note that the version number is off for Seer: it shows as 0.8.0.0 when I am actually running 1.1.

 

Cheers,

 

Valentin

**Comment by ccseer** [comment]
This bug might be delayed. This is a buy by the media framework. 
I have contacted the author.

And it seems like not all PC have this issue. But my PC have. : (

**Comment by ccseer** [comment]
Might release a new version with some window size updates.

**Comment by ccseer** [comment]
0.8.1 doesn't have this issue. 0.8.1 is using a older version of the media framework. But 0.8.1 is rendering video by CPU.

Sorry about this.

**Comment by vrodionov** [comment]
I don’t actually see much of a performance difference because of this on a day to day basis.

Bu the window management and stability for 0.8.x are better!

**Comment by ccseer** [comment]
I will let you know when I fixed it.

Maybe you can give next version a try before you roll back to 0.8.1.

vrodionov <notifications@github.com>于2016年11月10日周四 下午9:47写道：

**Comment by vrodionov** [comment]
Sure - I am always happy to help with the testing!

Get Outlook for iOS




On Thu, Nov 10, 2016 at 5:05 PM +0300, "Seer" <notifications@github.com> wrote:










I will let you know when I fixed it.



Maybe you can give next version a try before you roll back to 0.8.1.



vrodionov <notifications@github.com>于2016年11月10日周四 下午9:47写道：

**Comment by gerion23** [comment]
I have installed version 1.3.0 licensed and still have the problem with .avi videos, please some solution? Thank you

**Comment by ccseer** [comment]
fixed in  1.6.0

**Comment by djcurley89** [comment]
Glad to see this will be fixed in 1.6.0, but when will that be released? Mine hasn't even updated to 1.5.0 yet when checking for updates.

**Comment by ccseer** [comment]
1.6.0 will be released in 5 weeks.

For some reason, I can't release 1.5.0 public. 
If you want to install it, please email me.
